# Generated by Django 4.0.4 on 2022-05-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_alter_category_options_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique_for_date='pub_date', verbose_name='Слаг'),
        ),
    ]
